name: Testing for env variable 
on:
  push:
    paths:
      - .github/workflows/test-1.yml

jobs:
  env-testing:
    runs-on: ubuntu-24.04
    steps:
      - name: test the env var
        run: echo -e ${{ vars.ENV }} > .env
      - name: getting env
        run: cat .env
